



  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install utilties
          command: |
            yum install -y tar gzip

      - run:
          name: deploy infrastructure
          command: |
            aws cloudformation deploy \
                --region=us-east-1  \
                --template-file .circleci/files/VMs.yml \
                --stack-name "exam-simulator-${CIRCLE_WORKFLOW_ID:0:7}" \
                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
                --tags project=vodaexam
      - run:
          name: Add VM IPs to ansible inventory
          command: |
            aws ec2 describe-instances \
                --query 'Reservations[*].Instances[*].PublicIpAddress' \
                --filters "Name=tag:project,Values=exam-simulator-${CIRCLE_WORKFLOW_ID:0:7}" \
                --output text >> .circleci/ansible/inventory.txt
                cat .circleci/ansible/inventory.txt
                
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
            
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}